// Tailwind: the project builds its own CSS (works offline), and keeps the Tailwind CDN script the preview used. Where an
// element carries two conflicting utilities (e.g. "text-xs" and "text-[10px]"), the CDN and a local build break the tie
// differently; the built stylesheet is linked BEFORE the CDN script so the CDN's rules come last and the page matches the
// preview exactly. Without the CDN (offline, or the tag removed) the page is still styled, ties just resolve alphabetically.
// Turns a generated prototype page (one HTML file that loads React, Babel, Tailwind and icons from CDNs) into a
// Vite project that renders the same thing offline. The app code is copied verbatim; the CDN globals it relies on
// are provided from npm instead, and Tailwind is built locally from the prototype's own tailwind.config.

const CDN = {
  tailwind: /cdn\.tailwindcss\.com/,
  react: /unpkg\.com\/react(-dom)?@|@babel\/standalone/, // replaced by npm packages / compiled by Vite
  lucide: /lucide-react/,
}
const esc = (s: string) => s.replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]!)

export function prototypeProject(html: string, name: string, slug: string): Record<string, string> {
  const doc = new DOMParser().parseFromString(html, 'text/html')
  const scripts = [...doc.querySelectorAll('script')]
  const babel = scripts.filter((s) => /babel/i.test(s.type))
  const srcs = scripts.map((s) => s.getAttribute('src') ?? '')
  const tailwind = srcs.some((s) => CDN.tailwind.test(s))
  const lucide = srcs.some((s) => CDN.lucide.test(s))
  const title = doc.title || name
  const readme = (extra = '') => `# ${name} — Prototype

Generated by Forge. Run it with:

\`\`\`bash
npm install
npm run dev
\`\`\`

Then open the address Vite prints (usually http://localhost:5173).
${extra}`
  const common = {
    '.gitignore': 'node_modules\ndist\n',
    'vite.config.js': "import { defineConfig } from 'vite'\nimport react from '@vitejs/plugin-react'\n\nexport default defineConfig({ plugins: [react()] })\n",
  }
  const pkg = (deps: Record<string, string>, dev: Record<string, string>) => JSON.stringify({
    name: slug, private: true, version: '0.1.0', type: 'module',
    scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
    dependencies: deps, devDependencies: { '@vitejs/plugin-react': '^4.3.4', vite: '^5.4.11', ...dev },
  }, null, 2) + '\n'

  // No React app inside (plain HTML + Tailwind): the page already is the project, so ship it untouched.
  if (!babel.length) {
    return {
      ...common, 'index.html': html, 'package.json': pkg({}, {}),
      'README.md': readme(tailwind ? '\nThis page loads Tailwind from its CDN, so it needs an internet connection.\n' : ''),
    }
  }

  // ── head: keep fonts, inline styles and small inline scripts (e.g. the localStorage shim) in place ──
  const links = [...doc.head.querySelectorAll('link')].map((l) => l.outerHTML)
  const css = [...doc.querySelectorAll('style')].map((s) => s.textContent ?? '').join('\n\n').trim()
  const keep = scripts.filter((s) => {
    if (babel.includes(s)) return false
    const src = s.getAttribute('src')
    if (src) return !(CDN.react.test(src) || CDN.lucide.test(src)) // react/lucide come from npm; Tailwind's CDN and unknown libraries stay
    return !/window\.react\s*=\s*window\.React/.test(s.textContent ?? '') // replaced in main.jsx
  }).map((s) => s.outerHTML)
  const tailwindConfig = scripts.map((s) => /tailwind\.config\s*=\s*([\s\S]*?);?\s*$/.exec(s.textContent ?? '')?.[1]).find(Boolean)
  const bodyAttrs = [...doc.body.attributes].map((a) => ` ${a.name}="${esc(a.value)}"`).join('')

  const indexHtml = `<!doctype html>
<html lang="${esc(doc.documentElement.lang || 'en')}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${esc(title)}</title>
    ${[...links, '<link rel="stylesheet" href="/src/index.css" />', ...keep].join('\n    ')}
  </head>
  <body${bodyAttrs}>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`

  // The original page ran as a classic script with these globals; give the same names to the module.
  const main = `import React from 'react'
import * as ReactDOMAll from 'react-dom'
import * as ReactDOMClient from 'react-dom/client'
${lucide ? "import * as LucideReact from 'lucide-react'\n" : ''}
const ReactDOM = { ...ReactDOMAll, ...ReactDOMClient }
Object.assign(window, { React, ReactDOM, react: React${lucide ? ', LucideReact' : ''} })

${babel.map((s) => (s.textContent ?? '').trim()).join('\n\n')}
`

  // Same order as the live page: the prototype's own CSS first, Tailwind's generated CSS after it.
  const indexCss = `${css}\n\n${tailwind ? '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n' : ''}`

  return {
    ...common,
    'package.json': pkg(
      { react: '^18.3.1', 'react-dom': '^18.3.1', ...(lucide && { 'lucide-react': '0.263.1' }) }, // the icon set the prototype was built against
      tailwind ? { tailwindcss: '3.4.17', postcss: '^8.4.49', autoprefixer: '^10.4.20' } : {},
    ),
    ...(tailwind && {
      'postcss.config.js': 'export default { plugins: { tailwindcss: {}, autoprefixer: {} } }\n',
      'tailwind.config.js': `// The theme from the prototype (colours, fonts, radius).\nconst theme = ${tailwindConfig ?? '{}'}\n\nexport default { ...theme, content: ['./index.html', './src/**/*.{js,jsx}'] }\n`,
    }),
    'index.html': indexHtml,
    'src/main.jsx': main,
    'src/index.css': indexCss,
    'README.md': readme(`${tailwind ? `
## Styling

Tailwind CSS is built locally from \`tailwind.config.js\` and \`src/index.css\`, so the project is styled offline.
\`index.html\` also keeps the Tailwind CDN script the Forge preview uses, which makes the page match the preview pixel for
pixel when two classes on one element conflict. For a production app, delete that \`<script>\` tag and the inline
\`tailwind.config\` script after it.
` : ''}
## Project structure

\`\`\`
├── index.html           fonts and page shell
├── tailwind.config.js   the prototype's theme
├── src/index.css        the prototype's design tokens and styles
└── src/main.jsx         the whole app (split into files as it grows)
\`\`\`
`),
  }
}
